---

- name: Install Nginx
  import_tasks: install.yml
  when: install is defined and install|bool

- name: Setup Nginx
  import_tasks: setup.yml
  when: setup is defined and setup|bool

- name: Configure Nginx
  import_tasks: configure.yml
