---

nginx_version: 1.18.0
nginx_modules:
  - --with-threads
  - --with-file-aio
  - --with-http_ssl_module
  - --with-http_v2_module
  - --with-http_realip_module
  - --with-http_geoip_module
  - --with-http_gzip_static_module

nginx_extra_modules: []
nginx_config_template: nginx.conf.default.j2

clear: yes

# TODO: Prompt to ask user
server_name: example.com
app_root: /srv/app
app_user: root
app_group: root
