---

- name: Get Node Binary
  get_url:
    url: "https://nodejs.org/dist/v{{ node_version }}/node-v{{ node_version }}-linux-x64.tar.xz"
    dest: "/tmp/node-{{ node_version }}.tar.xz"
  register: node_binary

- name: Unarchive Node Binary
  unarchive:
    src: "{{ node_binary.dest }}"
    dest: /opt
    remote_src: true
  when: node_binary.changed

- name: Create /etc/profile.d/node.sh
  lineinfile:
    dest: /etc/profile.d/node.sh
    owner: root
    group: root
    mode: 0644
    create: yes
    regexp: "^export PATH=/opt/node-"
    line: "export PATH=/opt/node-v{{ node_version }}-linux-x64/bin:$PATH"

- name: Get Yarn Binary
  get_url:
    url: "https://yarnpkg.com/downloads/{{ yarn_version }}/yarn-v{{ yarn_version }}.tar.gz"
    dest: "/tmp/yarn-{{ yarn_version }}.tar.xz"
  when: yarn
  register: yarn_binary

- name: Unarchive Yarn Binary
  unarchive:
    src: "{{ yarn_binary.dest }}"
    dest: /opt
    remote_src: true
  when: yarn_binary.changed

- name: Create /etc/profile.d/yarn.sh
  lineinfile:
    dest: /etc/profile.d/yarn.sh
    owner: root
    group: root
    mode: 0644
    create: yes
    regexp: "^export PATH=/opt/yarn-{{ yarn_version }}"
    line: "export PATH=/opt/yarn-v{{ yarn_version }}/bin:$PATH"

- name: Clear Node & Yarn
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/node-{{ node_version }}.tar.xz"
    - "/tmp/yarn-{{ yarn_version }}.tar.gz"
  when: clear is defined and clear|bool
