---

- name: Setup authorized_keys
  authorized_key:
    user: "{{ app_user }}"
    state: present
    key: '{{ item }}'
  no_log: yes
  loop: "{{ authorized_keys }}"
  when: authorized_keys is defined

- name: Setup private key
  copy:
    content: "{{ deploy_key }}"
    dest: "/home/{{ app_user }}/.ssh/id_rsa"
    mode: 0600
    owner: deploy
    group: deploy
  no_log: yes
  when: deploy_key is defined
