---

- name: Get Passenger source code
  get_url:
    url: "http://s3.amazonaws.com/phusion-passenger/releases/passenger-{{ passenger_version }}.tar.gz"
    dest: "/tmp/passenger-{{ passenger_version }}.tar.gz"
  register: passenger_source

- name: Unarchive Passenger source code
  unarchive:
    src: "{{ passenger_source.dest }}"
    dest: /opt/
    owner: root
    group: root
    mode: 0755
    remote_src: true
  when: passenger_source.changed
  register: passenger_source_code

- name: Create /etc/profile.d/passenger.sh
  blockinfile:
    path: /etc/profile.d/passenger.sh
    owner: root
    group: root
    mode: 0644
    create: yes
    content: |
      export PATH=/opt/passenger-{{ passenger_version }}/bin:$PATH
      export PASSENGER_INSTANCE_REGISTRY_DIR=/var/run/passenger-instreg
  when: passenger_source_code.changed

- name: Create /var/run/passenger-instreg directory
  file:
    dest: /var/run/passenger-instreg
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0755
    state: directory

# TODO: Allow clear when restart user not root
- name: Fix /var/run/passenger-instreg removed
  lineinfile:
    dest: /etc/tmpfiles.d/passenger.conf
    owner: root
    group: root
    mode: 0644
    create: yes
    line: "D /var/run/passenger-instreg 0755 {{ app_user }} {{ app_group }}"

- name: Add Passenger Module
  set_fact:
    nginx_extra_options: "{{ nginx_extra_options + [ '--add-module=/opt/passenger-{{ passenger_version }}/src/nginx_module'] }}"
