---

- name: Setup Database User
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ postgres_username }}"
    password: "{{ postgres_password | default(omit) }}"

- name: Setup Database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ postgres_database }}"
    owner: "{{ postgres_username }}"
